"use strict";

// Local development server using only Node's standard library.
// The public application name is intentionally kept out of server output.
const http = require("http");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

// Force UTF-8 output so non-ASCII text does not render as boxes
try { require("child_process").execSync("chcp 65001 >nul", { shell: "cmd.exe" }); } catch {}

const ROOT = __dirname;
const PORT = Number(process.env.PORT || 3000);
const DATA_FILE = path.join(ROOT, "vexora-data.json");
const MIME = { ".html": "text/html; charset=utf-8", ".css": "text/css; charset=utf-8", ".js": "application/javascript; charset=utf-8", ".json": "application/json; charset=utf-8", ".svg": "image/svg+xml", ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".webp": "image/webp", ".ico": "image/x-icon" };
const rateBuckets = new Map();
const messageRateBuckets = new Map();
const pendingUsernames = new Set();
function chatRateLimit(req, key) { return rateLimit(req, `chat:${key}`, 30, 60000); }
const SESSION_MAX_AGE = 86400;
function rateLimit(req, key, max = 60, windowMs = 60000) { const now = Date.now(); const address = String(req.socket.remoteAddress || "local").replace(/^::ffff:/, ""); const bucketKey = `${address}:${key}`; const bucket = rateBuckets.get(bucketKey) || { start: now, count: 0 }; if (now - bucket.start > windowMs) { bucket.start = now; bucket.count = 0; } bucket.count += 1; rateBuckets.set(bucketKey, bucket); if (rateBuckets.size > 10000) for (const [entry, value] of rateBuckets) if (now - value.start > windowMs) rateBuckets.delete(entry); return bucket.count <= max; }
function sessionCookie(value, maxAge = SESSION_MAX_AGE) { const secure = process.env.NODE_ENV === "production" ? "; Secure" : ""; return `vexora_session=${encodeURIComponent(value)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAge}${secure}`; }
function hashPasswordSync(password) { const salt = crypto.randomBytes(16); const derived = crypto.pbkdf2Sync(String(password), salt, 120000, 32, "sha256"); return `pbkdf2$120000$${salt.toString("hex")}$${derived.toString("hex")}`; }
function bootstrapAdminPassword() {
  if (process.env.ADMIN_PASSWORD_HASH) return process.env.ADMIN_PASSWORD_HASH;
  const generated = crypto.randomBytes(9).toString("base64url");
  console.log("\n==============================================");
  console.log("[SETUP] هیچ ADMIN_PASSWORD_HASH ست نشده. یک پسورد موقت ادمین ساخته شد:");
  console.log("[SETUP] username: admin");
  console.log(`[SETUP] password: ${generated}`);
  console.log("[SETUP] همین الان ذخیره‌اش کن — دوباره نشون داده نمیشه. برای پسورد ثابت، ADMIN_PASSWORD_HASH رو توی .env تنظیم کن.");
  console.log("==============================================\n");
  return hashPasswordSync(generated);
}
function hashPassword(password) {
  return new Promise((resolve, reject) => {
    const salt = crypto.randomBytes(16);
    crypto.scrypt(String(password), salt, 32, { N: 16384, r: 8, p: 1 }, (error, derived) => {
      if (error) return reject(error);
      resolve(`scrypt$16384$8$1$${salt.toString("hex")}$${derived.toString("hex")}`);
    });
  });
}
function verifyPassword(password, stored) {
  return new Promise((resolve, reject) => {
    const parts = String(stored || "").split("$");
    if (parts[0] === "pbkdf2" && parts.length === 4) return crypto.pbkdf2(String(password), Buffer.from(parts[2], "hex"), Number(parts[1]), 32, "sha256", (error, derived) => { if (error) return reject(error); const expected = Buffer.from(parts[3], "hex"); resolve(expected.length === derived.length && crypto.timingSafeEqual(expected, derived)); });
    if (parts[0] !== "scrypt" || parts.length !== 6) return resolve(false);
    crypto.scrypt(String(password), Buffer.from(parts[4], "hex"), 32, { N: Number(parts[1]), r: Number(parts[2]), p: Number(parts[3]) }, (error, derived) => { if (error) return reject(error); const expected = Buffer.from(parts[5], "hex"); resolve(expected.length === derived.length && crypto.timingSafeEqual(expected, derived)); });
  });
}
function safeRequest(req, res, key, max) { if (rateLimit(req, key, max)) return true; reply(res, 429, { error: "تعداد درخواست‌ها بیش از حد مجاز است." }); return false; }
function sameOrigin(req) { const origin = String(req.headers.origin || ""); const expectedHttp = `http://${req.headers.host}`; const expectedHttps = `https://${req.headers.host}`; if (origin) return origin === expectedHttp || origin === expectedHttps; const cookie = String(req.headers.cookie || ""); return !cookie.includes("vexora_session="); }

const initialData = {
  users: [
    { id: "u-admin", username: "admin", name: "ادمین", password: bootstrapAdminPassword(), score: 9999, favoriteGame: "—", avatar: "A", role: "admin", status: "approved", friends: [] }
  ],
  messages: [],
  communityMessages: [],
  groups: [],
  groupMembers: [],
  groupMessages: [],
  groupJoinRequests: [],
  news: [],
  follows: [],
  notifications: [],
  sessions: [],
  reports: []
};

const seedNews = [
  { id: "n-gta6", title: "جزئیات تازه از یکی از موردانتظارترین بازی‌های سال", excerpt: "نگاهی به خبرهای مهم این هفته از دنیای بازی و به‌روزرسانی‌های استودیوها.", text: "تازه‌ترین گزارش‌ها از روند توسعه و برنامه‌های آینده منتشر شده است. این خبر با تمرکز بر اطلاعات قابل بررسی و بدون شایعه‌پردازی گردآوری شده است.", category: "gaming", tags: ["Gaming", "Updates"], author: "admin", authorName: "ادمین", verified: true, image: "", likes: [], comments: [], createdAt: new Date().toISOString(), publishedAt: new Date().toISOString(), views: 2400, status: "published" },
  { id: "n-esports", title: "تقویم رقابت‌های مهم ورزش‌های الکترونیک", excerpt: "مسابقات مهم این ماه را از دست ندهید؛ برنامه و نتایج در جامعه گیمرها دنبال می‌شود.", text: "از رقابت‌های تیمی تا مسابقات انفرادی، رویدادهای مهم ماه را در دسته ورزش الکترونیک دنبال کنید.", category: "esports", tags: ["Esports"], author: "admin", authorName: "ادمین", verified: true, image: "", likes: [], comments: [], createdAt: new Date(Date.now() - 86400000).toISOString(), publishedAt: new Date(Date.now() - 86400000).toISOString(), views: 980, status: "published" },
  { id: "n-hardware", title: "راهنمای کوتاه ارتقای سیستم برای بازی روان‌تر", excerpt: "قبل از خرید قطعه جدید، این نکات را برای انتخاب هوشمندانه بررسی کنید.", text: "ارتقای سیستم همیشه به معنای خرید گران‌ترین قطعه نیست. ابتدا گلوگاه سیستم را پیدا کنید و سپس اولویت ارتقا را مشخص کنید.", category: "hardware", tags: ["Hardware", "PC"], author: "admin", authorName: "ادمین", verified: true, image: "", likes: [], comments: [], createdAt: new Date(Date.now() - 172800000).toISOString(), publishedAt: new Date(Date.now() - 172800000).toISOString(), views: 640, status: "published" }
];
function normalizeLikeData(data) {
  let changed = false;
  (data.news || []).forEach(item => {
    const likes = Array.isArray(item.likes) ? [...new Set(item.likes.filter(Boolean))] : [];
    if (JSON.stringify(likes) !== JSON.stringify(item.likes || [])) { item.likes = likes; changed = true; }
    (item.comments || []).forEach(comment => {
      const commentLikes = Array.isArray(comment.likes) ? [...new Set(comment.likes.filter(Boolean))] : [];
      if (JSON.stringify(commentLikes) !== JSON.stringify(comment.likes || [])) { comment.likes = commentLikes; changed = true; }
    });
  });
  return changed;
}
function loadData() { try { const data = JSON.parse(fs.readFileSync(DATA_FILE, "utf8")); let changed = false; if (!Array.isArray(data.news) || !data.news.length) { data.news = structuredClone(seedNews); changed = true; } data.groups = Array.isArray(data.groups) ? data.groups : []; data.groupMembers = Array.isArray(data.groupMembers) ? data.groupMembers : []; data.groupMessages = Array.isArray(data.groupMessages) ? data.groupMessages : []; data.groupJoinRequests = Array.isArray(data.groupJoinRequests) ? data.groupJoinRequests : []; if (process.env.NODE_ENV !== "production" && !data.groups.some(group => group.name === "VEXORA TEST GROUP")) { const now = new Date().toISOString(); const testGroup = { id: "group-vexora-test", name: "VEXORA TEST GROUP", description: "گروه آزمایشی برای تست سیستم گروه‌های VEXORA CHAT", avatar: "", type: "public", leaderId: "u-admin", maxMembers: 50, createdAt: now, updatedAt: now }; data.groups.push(testGroup); data.groupMembers.push({ id: "gm-vexora-test-admin", groupId: testGroup.id, userId: "u-admin", role: "leader", joinedAt: now }); changed = true; } data.sessions = Array.isArray(data.sessions) ? data.sessions.filter(session => Date.now() - new Date(session.createdAt).getTime() < 86400000) : []; data.reports = Array.isArray(data.reports) ? data.reports : []; data.users = Array.isArray(data.users) ? data.users : []; const usernames = new Set(); data.users.forEach(user => { const normalized = String(user.username || "").trim().toLowerCase(); if (user.username !== normalized) { user.username = normalized; changed = true; } if (user.password && !String(user.password).startsWith("pbkdf2$") && !String(user.password).startsWith("scrypt$")) { user.password = hashPasswordSync(user.password); changed = true; } if (usernames.has(normalized)) throw new Error("Duplicate username in database"); usernames.add(normalized); }); if (normalizeLikeData(data)) changed = true; if (changed) saveData(data); return data; } catch { const data = structuredClone(initialData); data.news = structuredClone(seedNews); return data; } }
function saveData(data) { fs.writeFileSync(DATA_FILE, JSON.stringify(data, null, 2), "utf8"); }
function injectNonce(html, nonce) { return html.replace(/<script(\s[^>]*)?>/gi, (match, attrs = "") => { if (/\bsrc\s*=/i.test(attrs)) return match; return `<script nonce="${nonce}"${attrs}>`; }); }
function securityHeaders(nonce) { const scriptSrc = nonce ? `'self' 'nonce-${nonce}'` : "'self'"; return { "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff", "Referrer-Policy": "no-referrer", "X-Frame-Options": "DENY", "Cross-Origin-Opener-Policy": "same-origin", "Cross-Origin-Resource-Policy": "same-origin", "Permissions-Policy": "camera=(), microphone=(), geolocation=(), payment=()", "Content-Security-Policy": `default-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src ${scriptSrc}; img-src 'self' data: blob:; connect-src 'self'` }; }
function reply(res, code, body, extraHeaders = {}) { res.writeHead(code, { "Content-Type": "application/json; charset=utf-8", ...securityHeaders(), ...extraHeaders }); res.end(JSON.stringify(body)); }
function readBody(req) { return new Promise((resolve, reject) => { let value = ""; let tooLarge = false; let settled = false; const fail = error => { if (settled) return; settled = true; reject(error); }; req.on("data", chunk => { if (tooLarge || settled) return; value += chunk; if (value.length > 1e6) { tooLarge = true; fail(new Error("بدنهٔ درخواست بیش از حد مجاز است.")); req.destroy(); } }); req.on("end", () => { if (tooLarge || settled) return; try { settled = true; resolve(value ? JSON.parse(value) : {}); } catch { fail(new Error("بدنهٔ درخواست نامعتبر است.")); } }); req.on("error", fail); }); }
function token() { return crypto.randomBytes(32).toString("hex"); }
function publicUser(user) { const { password, ...safe } = user; return safe; }
function validateUsername(value) {
  const username = String(value || "").trim().toLowerCase();
  if (!/^[a-z0-9_]{3,24}$/.test(username)) return { username, error: "نام کاربری باید ۳ تا ۲۴ کاراکتر انگلیسی، عدد یا _ باشد و فاصله نداشته باشد." };
  return { username };
}
function validatePassword(value, repeat) {
  const password = String(value || "");
  if (!password) return "رمز عبور نمی‌تواند خالی باشد.";
  if (password.length < 8) return "رمز عبور باید حداقل 8 کاراکتر باشد.";
  if (password.length > 128) return "رمز عبور نمی‌تواند بیشتر از 128 کاراکتر باشد.";
  if (/\s/.test(password)) return "رمز عبور نباید شامل فاصله باشد.";
  if (!/[A-Z]/.test(password)) return "رمز عبور باید حداقل یک حرف بزرگ انگلیسی داشته باشد.";
  if (!/[a-z]/.test(password)) return "رمز عبور باید حداقل یک حرف کوچک انگلیسی داشته باشد.";
  if (!/[0-9]/.test(password)) return "رمز عبور باید حداقل یک عدد داشته باشد.";
  if (repeat !== undefined && password !== String(repeat)) return "رمز عبور و تکرار رمز عبور یکسان نیستند.";
  return "";
}
function sessionUser(data, req) { const header = String(req.headers.authorization || ""); const cookies = Object.fromEntries(String(req.headers.cookie || "").split(";").map(part => part.trim().split("=")).filter(part => part.length === 2).map(([key, ...value]) => [key, decodeURIComponent(value.join("="))])); const value = header.startsWith("Bearer ") ? header.slice(7).trim() : cookies.vexora_session || ""; if (!/^[a-f0-9]{64}$/.test(value)) return null; const session = data.sessions.find(item => item.token === value && Date.now() - new Date(item.createdAt).getTime() < SESSION_MAX_AGE * 1000); return session ? data.users.find(user => user.id === session.userId && user.status === "approved") : null; }
function requireUser(data, req, res) { const user = sessionUser(data, req); if (!user) { reply(res, 401, { error: "برای این عملیات باید وارد شوید." }); return null; } return user; }
function requireAdmin(data, req, res) { const user = requireUser(data, req, res); if (!user) return null; if (user.role !== "admin") { reply(res, 403, { error: "دسترسی مدیر لازم است." }); return null; } return user; }
function notify(data, username, type, from, text) { data.notifications = data.notifications || []; data.notifications.push({ id: `no-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`, user: username, type, from, text, read: false, createdAt: new Date().toISOString() }); }
function friendsOf(data, username) { const user = data.users.find(item => item.username === username); return Array.isArray(user && user.friends) ? user.friends : []; }
function isFriend(data, a, b) { return friendsOf(data, a).includes(b); }
function lastMessageOf(data, a, b) { return (data.messages || []).filter(m => (m.conversation === a && m.sender === b) || (m.conversation === b && m.sender === a)).sort((x, y) => new Date(y.createdAt) - new Date(x.createdAt))[0] || null; }
function communityMessageView(data, item) { const sender = data.users.find(user => user.username === item.sender); return { ...item, name: sender?.name || item.sender, avatar: sender?.avatar || item.sender?.[0] || "؟" }; }
function groupById(data, id) { return data.groups.find(group => group.id === id); }
function groupMember(data, groupId, userId) { return data.groupMembers.find(member => member.groupId === groupId && member.userId === userId); }
function groupView(data, group, viewer) { const leader = data.users.find(user => user.id === group.leaderId); const members = data.groupMembers.filter(member => member.groupId === group.id).map(member => { const user = data.users.find(item => item.id === member.userId); return { ...member, username: user?.username || "کاربر", name: user?.name || user?.username || "کاربر", avatar: user?.avatar || user?.username?.[0] || "؟" }; }); return { ...group, leader: leader ? { id: leader.id, username: leader.username, name: leader.name, avatar: leader.avatar } : null, members, memberCount: members.length, isMember: !!viewer && members.some(member => member.userId === viewer.id), isLeader: !!viewer && group.leaderId === viewer.id, pendingRequest: !!viewer && data.groupJoinRequests.some(request => request.groupId === group.id && request.userId === viewer.id && request.status === "pending") }; }
function groupIdParam(url) { const match = url.pathname.match(/^\/api\/groups\/([^/]+)/); return match ? decodeURIComponent(match[1]) : null; }

async function api(req, res, url) {
  const bucket = url.pathname.startsWith("/api/login") ? "login" : url.pathname.startsWith("/api/register") ? "register" : "api";
  if (!safeRequest(req, res, bucket, bucket === "login" ? 8 : bucket === "register" ? 10 : 180)) return;
  if (["POST", "PUT", "PATCH", "DELETE"].includes(req.method) && !sameOrigin(req)) return reply(res, 403, { error: "مبدأ درخواست معتبر نیست." });
  if (["POST", "PUT", "PATCH", "DELETE"].includes(req.method) && String(req.headers["content-type"] || "").split(";")[0].toLowerCase() !== "application/json") return reply(res, 415, { error: "نوع محتوای درخواست باید JSON باشد." });
  if (Number(req.headers["content-length"] || 0) > 1000000) return reply(res, 413, { error: "درخواست بیش از حد مجاز است." });
  const data = loadData();
  const viewer = sessionUser(data, req);
  const me = viewer ? viewer.username : "";
  if (req.method === "GET" && url.pathname === "/api/news") {
    const category = (url.searchParams.get("category") || "all").trim().toLowerCase();
    const list = (data.news || []).filter(item => item.status !== "draft").filter(item => category === "all" || String(item.category || "gaming").toLowerCase() === category).map(item => ({ ...item, verified: true, isOfficial: item.isOfficial === true || item.author === "admin", likes: (item.likes || []).length, liked: !!me && (item.likes || []).includes(me), comments: (item.comments || []).length })).sort((a, b) => new Date(b.publishedAt || b.createdAt) - new Date(a.publishedAt || a.createdAt));
    return reply(res, 200, { featured: list[0] || null, news: list });
  }
  const newsMatch = url.pathname.match(/^\/api\/news\/([^/]+)$/);
  if (req.method === "GET" && newsMatch) { const item = (data.news || []).find(entry => entry.id === newsMatch[1]); if (!item || item.status === "draft") return reply(res, 404, { error: "خبر پیدا نشد." }); item.views = Number(item.views || 0) + 1; saveData(data); const related = (data.news || []).filter(entry => entry.id !== item.id && entry.status !== "draft" && entry.category === item.category).slice(0, 3); return reply(res, 200, { news: { ...item, verified: true, isOfficial: item.isOfficial === true || item.author === "admin", likes: (item.likes || []).length, liked: !!me && (item.likes || []).includes(me), related } }); }
  if (req.method === "GET" && url.pathname === "/api/users") { const query = (url.searchParams.get("query") || "").trim().toLowerCase().replace(/^@/, ""); const list = data.users.filter(u => u.status !== "pending").map(publicUser).filter(user => !query || user.username.toLowerCase().includes(query) || String(user.name || "").toLowerCase().includes(query)).slice(0, 12); return reply(res, 200, { users: list }); }
  if (req.method === "GET" && url.pathname === "/api/leaderboard") { const players = data.users.filter(user => user.status === "approved").map(user => ({ ...publicUser(user), followers: data.follows.filter(entry => entry.target === user.username).length, likes: (data.news || []).reduce((total, item) => total + (item.likes || []).filter(name => name === user.username).length, 0) })).sort((a, b) => Number(b.score || 0) - Number(a.score || 0)).slice(0, 50); return reply(res, 200, { players }); }
  if (req.method === "POST" && url.pathname === "/api/news") { const owner = requireUser(data, req, res); if (!owner) return; const body = await readBody(req); const title = String(body.title || "").trim(); const text = String(body.text || "").trim(); const author = owner.username; if (!title || title.length > 140 || !text || text.length > 3000 || !owner) return reply(res, 400, { error:"عنوان، متن و حساب کاربری معتبر لازم است." }); const image = String(body.image || ""); if (image && (!image.startsWith("data:image/") || image.length > 900000)) return reply(res, 400, { error:"تصویر معتبر نیست یا حجم آن بیش از حد مجاز است." }); const tags = String(body.tags || "").split(/\s+/).filter(value => value.startsWith("#")).slice(0, 8).map(value => value.slice(1, 33)); const tagText = tags.join(" ").toLowerCase(); const requestedCategory = String(body.category || "gaming").trim().toLowerCase(); const category = tagText.includes("esport") || tagText.includes("ورزش") ? "esports" : tagText.includes("hardware") || tagText.includes("سخت") || tagText.includes("pc") ? "hardware" : ["gaming", "esports", "hardware"].includes(requestedCategory) ? requestedCategory : "gaming"; const item = { id:`n-${Date.now()}`, title, excerpt: String(body.excerpt || text.slice(0, 180)).trim(), text, category, game:String(body.game || "").trim(), tags, author:owner.username, authorName:owner.name, verified:true, isOfficial:owner.role === "admin", image, likes:[], comments:[], createdAt:new Date().toISOString(), publishedAt:new Date().toISOString(), views:0, status:"published" }; data.news = data.news || []; data.news.push(item); saveData(data); return reply(res, 201, { news:{ ...item, likes:0, liked:false } }); }
  const likeMatch = url.pathname.match(/^\/api\/news\/([^/]+)\/like$/);
  if (req.method === "POST" && likeMatch) { const viewer = requireUser(data, req, res); if (!viewer) return; const body = await readBody(req); const item = (data.news || []).find(entry => entry.id === likeMatch[1]); if (!item) return reply(res, 404, { error:"خبر پیدا نشد." }); const username = viewer.username; const uniqueLikes = [...new Set(Array.isArray(item.likes) ? item.likes.filter(Boolean) : [])]; const currentlyLiked = uniqueLikes.includes(username); const desiredLiked = typeof body.liked === "boolean" ? body.liked : !currentlyLiked; item.likes = desiredLiked ? [...uniqueLikes.filter(name => name !== username), username] : uniqueLikes.filter(name => name !== username); saveData(data); return reply(res, 200, { likes:item.likes.length, liked:desiredLiked }); }
  const commentMatch = url.pathname.match(/^\/api\/news\/([^/]+)\/comment$/);
  if (req.method === "POST" && commentMatch) { const user = requireUser(data, req, res); if (!user) return; const body = await readBody(req); const item = (data.news || []).find(entry => entry.id === commentMatch[1]); const text = String(body.text || "").trim(); if (!item || !text || text.length > 300 || !user) return reply(res, 400, { error:"متن نظر یا حساب کاربری معتبر نیست." }); const comment = { id:`c-${Date.now()}`, user:user.username, name:user.name, text, likes:[], createdAt:new Date().toISOString() }; item.comments = item.comments || []; item.comments.push(comment); if (item.author && item.author !== user.username) notify(data, item.author, "comment", user.username, "@" + user.username + " روی خبر شما نظر داد: " + text.slice(0, 60)); saveData(data); return reply(res, 201, { comment }); }
  const commentLikeMatch = url.pathname.match(/^\/api\/news\/([^/]+)\/comment\/([^/]+)\/like$/);
  if (req.method === "POST" && commentLikeMatch) { const viewer = requireUser(data, req, res); if (!viewer) return; const body = await readBody(req); const item = (data.news || []).find(entry => entry.id === commentLikeMatch[1]); const comment = item && (item.comments || []).find(entry => entry.id === commentLikeMatch[2]); if (!comment) return reply(res, 404, { error: "نظر پیدا نشد." }); const uniqueLikes = [...new Set(Array.isArray(comment.likes) ? comment.likes.filter(Boolean) : [])]; const currentlyLiked = uniqueLikes.includes(viewer.username); const desiredLiked = typeof body.liked === "boolean" ? body.liked : !currentlyLiked; comment.likes = desiredLiked ? [...uniqueLikes.filter(name => name !== viewer.username), viewer.username] : uniqueLikes.filter(name => name !== viewer.username); saveData(data); return reply(res, 200, { likes: comment.likes.length, liked: desiredLiked }); }
  if (req.method === "POST" && url.pathname === "/api/follow") { const viewer = requireUser(data, req, res); if (!viewer) return; const body = await readBody(req); const follower = viewer.username; const target = String(body.target || "").toLowerCase(); if (follower === target || !data.users.some(u => u.username === follower) || !data.users.some(u => u.username === target)) return reply(res, 400, { error:"درخواست فالو معتبر نیست." }); const index = data.follows.findIndex(entry => entry.follower === follower && entry.target === target); if (index >= 0) { data.follows.splice(index, 1); saveData(data); return reply(res, 200, { following:false }); } data.follows.push({ follower, target, createdAt:new Date().toISOString() }); notify(data, target, "follow", follower, "@" + follower + " شما را دنبال کرد."); saveData(data); return reply(res, 200, { following:true }); }
  const replyMatch = url.pathname.match(/^\/api\/news\/([^/]+)\/comment\/(\d+)$/);
  if (req.method === "POST" && replyMatch) { const user = requireUser(data, req, res); if (!user) return; const body = await readBody(req); const item = (data.news || []).find(entry => entry.id === replyMatch[1]); const parentIndex = Number(replyMatch[2]); const parent = item && (item.comments || [])[parentIndex]; const text = String(body.text || "").trim(); if (!item || !parent || !text || text.length > 300 || !user) return reply(res, 400, { error:"متن پاسخ یا حساب کاربری معتبر نیست." }); const comment = { id:`c-${Date.now()}`, user:user.username, name:user.name, text, likes:[], replyTo: parent.user, replyToName: parent.name, createdAt:new Date().toISOString() }; item.comments.push(comment); if (parent.user && parent.user !== user.username) notify(data, parent.user, "reply", user.username, "@" + user.username + " به نظر شما پاسخ داد: " + text.slice(0, 60)); saveData(data); return reply(res, 201, { comment }); }
  if (req.method === "GET" && /^\/api\/users\/[^/]+$/.test(url.pathname)) { const username = decodeURIComponent(url.pathname.split("/").pop()).replace(/^@/, "").toLowerCase(); const user = data.users.find(item => item.username.toLowerCase() === username); if (!user) return reply(res, 404, { error:"کاربر پیدا نشد." }); return reply(res, 200, { profile:{ ...publicUser(user), followers: data.follows.filter(entry => entry.target === user.username).length + Math.max(120, Math.round(user.score * .72)), following: data.follows.filter(entry => entry.follower === user.username).length + Math.max(8, Math.round(user.score / 190)), verified:true, isFollowing: !!me && data.follows.some(entry => entry.follower === me && entry.target === user.username) } }); }
  if (req.method === "GET" && url.pathname === "/api/community/messages") { const messages = Array.isArray(data.communityMessages) ? data.communityMessages.slice(-100).map(item => communityMessageView(data, item)) : []; return reply(res, 200, { messages }); }
  if (req.method === "POST" && url.pathname === "/api/community/messages") { const viewer = requireUser(data, req, res); if (!viewer) return; if (!chatRateLimit(req, "global")) return reply(res, 429, { error: "ارسال پیام بیش از حد مجاز است؛ کمی بعد دوباره تلاش کنید." }); const body = await readBody(req); const text = String(body.text || "").trim(); if (!text || text.length > 500) return reply(res, 400, { error: "متن پیام معتبر نیست." }); data.communityMessages = Array.isArray(data.communityMessages) ? data.communityMessages : []; const message = { id: `cm-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`, sender: viewer.username, text, createdAt: new Date().toISOString() }; data.communityMessages.push(message); data.communityMessages = data.communityMessages.slice(-500); saveData(data); return reply(res, 201, { message: communityMessageView(data, message) }); }
  if (req.method === "GET" && url.pathname === "/api/groups") { return reply(res, 200, { groups: data.groups.map(group => groupView(data, group, viewer)) }); }
  const groupId = groupIdParam(url);
  if (groupId && req.method === "GET" && url.pathname === `/api/groups/${encodeURIComponent(groupId)}`) { const group = groupById(data, groupId); if (!group) return reply(res, 404, { error: "گروه پیدا نشد." }); const view = groupView(data, group, viewer); if (!view.isMember && !view.isLeader) view.members = []; return reply(res, 200, { group: view }); }
  if (req.method === "POST" && url.pathname === "/api/groups") { const owner = requireUser(data, req, res); if (!owner) return; const body = await readBody(req); const name = String(body.name || "").trim(); const description = String(body.description || "").trim(); const type = body.type === "private" ? "private" : "public"; const avatar = String(body.avatar || ""); if (!name) return reply(res, 400, { error: "لطفاً نام گروه را وارد کنید." }); if (name.length > 80 || description.length > 500 || (avatar && (!avatar.startsWith("data:image/") || avatar.length > 700000))) return reply(res, 400, { error: "اطلاعات گروه معتبر نیست." }); const now = new Date().toISOString(); const group = { id: `group-${crypto.randomUUID()}`, name, description, avatar, type, leaderId: owner.id, maxMembers: 50, createdAt: now, updatedAt: now }; data.groups.push(group); data.groupMembers.push({ id: `gm-${crypto.randomUUID()}`, groupId: group.id, userId: owner.id, role: "leader", joinedAt: now }); saveData(data); return reply(res, 201, { group: groupView(data, group, owner) }); }
  if (groupId && req.method === "POST" && url.pathname === `/api/groups/${encodeURIComponent(groupId)}/join`) { const member = requireUser(data, req, res); if (!member) return; const group = groupById(data, groupId); if (!group) return reply(res, 404, { error: "گروه پیدا نشد." }); if (groupMember(data, groupId, member.id)) return reply(res, 409, { error: "شما عضو این گروه هستید." }); if (data.groupMembers.filter(item => item.groupId === groupId).length >= 50) return reply(res, 409, { error: "ظرفیت این گروه تکمیل است." }); if (group.type === "private") { const existing = data.groupJoinRequests.find(item => item.groupId === groupId && item.userId === member.id && item.status === "pending"); if (!existing) data.groupJoinRequests.push({ id: `gj-${crypto.randomUUID()}`, groupId, userId: member.id, status: "pending", createdAt: new Date().toISOString() }); saveData(data); return reply(res, 202, { requested: true }); } data.groupMembers.push({ id: `gm-${crypto.randomUUID()}`, groupId, userId: member.id, role: "member", joinedAt: new Date().toISOString() }); group.updatedAt = new Date().toISOString(); saveData(data); return reply(res, 201, { group: groupView(data, group, member) }); }
  if (groupId && req.method === "POST" && url.pathname === `/api/groups/${encodeURIComponent(groupId)}/transfer-leader`) { const leader = requireUser(data, req, res); const group = groupById(data, groupId); if (!leader || !group || group.leaderId !== leader.id) return reply(res, 403, { error: "فقط لیدر می‌تواند لیدر جدید انتخاب کند." }); const body = await readBody(req); const next = data.users.find(user => user.id === body.userId); if (!next || !groupMember(data, groupId, next.id)) return reply(res, 400, { error: "لیدر جدید باید عضو گروه باشد." }); group.leaderId = next.id; const oldMembership = groupMember(data, groupId, leader.id); const newMembership = groupMember(data, groupId, next.id); if (oldMembership) oldMembership.role = "member"; if (newMembership) newMembership.role = "leader"; group.updatedAt = new Date().toISOString(); saveData(data); return reply(res, 200, { group: groupView(data, group, leader) }); }
  if (groupId && req.method === "DELETE" && url.pathname === `/api/groups/${encodeURIComponent(groupId)}/members`) { const leader = requireUser(data, req, res); const group = groupById(data, groupId); if (!leader || !group || group.leaderId !== leader.id) return reply(res, 403, { error: "فقط لیدر می‌تواند اعضا را حذف کند." }); const body = await readBody(req); const member = groupMember(data, groupId, body.userId); if (!member || member.userId === leader.id) return reply(res, 400, { error: "عضو معتبر نیست." }); data.groupMembers = data.groupMembers.filter(item => item !== member); saveData(data); return reply(res, 200, { removed: true }); }
  if (groupId && req.method === "POST" && url.pathname === `/api/groups/${encodeURIComponent(groupId)}/leave`) { const member = requireUser(data, req, res); if (!member) return; const group = groupById(data, groupId); const membership = group && groupMember(data, groupId, member.id); if (!group || !membership) return reply(res, 404, { error: "عضویت پیدا نشد." }); if (group.leaderId === member.id) return reply(res, 403, { error: "لیدر باید ابتدا لیدر جدیدی انتخاب کند." }); data.groupMembers = data.groupMembers.filter(item => item !== membership); saveData(data); return reply(res, 200, { left: true }); }
  if (groupId && req.method === "GET" && url.pathname === `/api/groups/${encodeURIComponent(groupId)}/messages`) { const member = requireUser(data, req, res); if (!member) return; if (!groupMember(data, groupId, member.id)) return reply(res, 403, { error: "فقط اعضای گروه به چت دسترسی دارند." }); const messages = data.groupMessages.filter(item => item.groupId === groupId).slice(-100).map(item => ({ ...item, user: data.users.find(user => user.id === item.userId)?.username || "کاربر" })); return reply(res, 200, { messages }); }
  if (groupId && req.method === "POST" && url.pathname === `/api/groups/${encodeURIComponent(groupId)}/messages`) { const member = requireUser(data, req, res); if (!member) return; if (!groupMember(data, groupId, member.id)) return reply(res, 403, { error: "فقط اعضای گروه به چت دسترسی دارند." }); const body = await readBody(req); const text = String(body.text || "").trim(); if (!text || text.length > 500) return reply(res, 400, { error: "متن پیام معتبر نیست." }); const message = { id: `gm-${crypto.randomUUID()}`, groupId, userId: member.id, message: text, createdAt: new Date().toISOString() }; data.groupMessages.push(message); saveData(data); return reply(res, 201, { message: { ...message, user: member.username } }); }
  if (groupId && req.method === "PATCH" && url.pathname === `/api/groups/${encodeURIComponent(groupId)}`) { const leader = requireUser(data, req, res); if (!leader) return; const group = groupById(data, groupId); if (!group || group.leaderId !== leader.id) return reply(res, 403, { error: "فقط لیدر می‌تواند اطلاعات گروه را ویرایش کند." }); const body = await readBody(req); const name = String(body.name ?? group.name).trim(); const description = String(body.description ?? group.description).trim(); const avatar = String(body.avatar ?? group.avatar); if (!name) return reply(res, 400, { error: "لطفاً نام گروه را وارد کنید." }); if (name.length > 80 || description.length > 500 || (avatar && (!avatar.startsWith("data:image/") || avatar.length > 700000))) return reply(res, 400, { error: "اطلاعات گروه معتبر نیست." }); Object.assign(group, { name, description, avatar, updatedAt: new Date().toISOString() }); saveData(data); return reply(res, 200, { group: groupView(data, group, leader) }); }
  if (groupId && req.method === "GET" && url.pathname === `/api/groups/${encodeURIComponent(groupId)}/requests`) { const leader = requireUser(data, req, res); if (!leader) return; const group = groupById(data, groupId); if (!group || group.leaderId !== leader.id) return reply(res, 403, { error: "فقط لیدر می‌تواند درخواست‌ها را ببیند." }); return reply(res, 200, { requests: data.groupJoinRequests.filter(item => item.groupId === groupId && item.status === "pending").map(item => ({ ...item, user: publicUser(data.users.find(user => user.id === item.userId) || {}) })) }); }
  if (groupId && req.method === "POST" && url.pathname === `/api/groups/${encodeURIComponent(groupId)}/requests`) { const leader = requireUser(data, req, res); const group = groupById(data, groupId); if (!leader || !group || group.leaderId !== leader.id) return reply(res, 403, { error: "فقط لیدر می‌تواند درخواست‌ها را مدیریت کند." }); const body = await readBody(req); const request = data.groupJoinRequests.find(item => item.id === body.requestId && item.groupId === groupId && item.status === "pending"); if (!request) return reply(res, 404, { error: "درخواست پیدا نشد." }); if (body.action === "approve") { if (data.groupMembers.filter(item => item.groupId === groupId).length >= 50) return reply(res, 409, { error: "ظرفیت این گروه تکمیل است." }); data.groupMembers.push({ id: `gm-${crypto.randomUUID()}`, groupId: groupId, userId: request.userId, role: "member", joinedAt: new Date().toISOString() }); request.status = "approved"; } else request.status = "rejected"; saveData(data); return reply(res, 200, { request }); }
  if (groupId && req.method === "DELETE" && url.pathname === `/api/groups/${encodeURIComponent(groupId)}`) { const leader = requireUser(data, req, res); if (!leader) return; const group = groupById(data, groupId); if (!group) return reply(res, 404, { error: "گروه پیدا نشد." }); if (group.leaderId !== leader.id) return reply(res, 403, { error: "فقط لیدر می‌تواند گروه را حذف کند." }); data.groups = data.groups.filter(item => item.id !== groupId); data.groupMembers = data.groupMembers.filter(item => item.groupId !== groupId); data.groupMessages = data.groupMessages.filter(item => item.groupId !== groupId); data.groupJoinRequests = data.groupJoinRequests.filter(item => item.groupId !== groupId); saveData(data); return reply(res, 200, { deleted: true }); }
  if (req.method === "GET" && url.pathname === "/api/messages") { const viewer = requireUser(data, req, res); if (!viewer) return; const conversation = (url.searchParams.get("conversation") || "").toLowerCase().replace(/^@/, ""); const messages = data.messages.filter(m => (m.conversation === conversation && m.sender === viewer.username) || (m.conversation === viewer.username && m.sender === conversation)); if (url.searchParams.get("after")) { const after = url.searchParams.get("after"); return reply(res, 200, { messages: messages.filter(m => m.id > `m-${after}` || new Date(m.createdAt) > new Date(Number(after) || 0)) }); } messages.forEach(m => { if (m.conversation === conversation && m.sender === conversation && !m.read) { m.read = true; } }); saveData(data); return reply(res, 200, { messages }); }
  if (req.method === "POST" && url.pathname === "/api/messages") { const viewer = requireUser(data, req, res); if (!viewer) return; if (!chatRateLimit(req, viewer.username)) return reply(res, 429, { error: "ارسال پیام بیش از حد مجاز است؛ کمی بعد دوباره تلاش کنید." }); const body = await readBody(req); const text = String(body.text || "").trim(); const conversation = String(body.conversation || "").toLowerCase().replace(/^@/, ""); if (!text || text.length > 500 || !conversation || conversation === viewer.username) return reply(res, 400, { error: "پیام یا گفتگو معتبر نیست." }); if (!data.users.some(user => user.username === conversation && user.status === "approved")) return reply(res, 404, { error: "کاربر گفتگو پیدا نشد." }); const message = { id: `m-${Date.now()}`, conversation, sender: viewer.username, text, createdAt: new Date().toISOString(), read: false }; data.messages.push(message); saveData(data); return reply(res, 201, { message }); }
  if (req.method === "GET" && url.pathname === "/api/register/status") { const username = (url.searchParams.get("username") || "").trim().toLowerCase(); const user = data.users.find(u => u.username === username); if (!user) return reply(res, 200, { status: "rejected" }); let value = null; if (user.status === "approved") { value = token(); data.sessions.push({ token: value, userId: user.id, createdAt: new Date().toISOString() }); saveData(data); } return reply(res, 200, { status: user.status, user: user.status === "approved" ? publicUser(user) : null }, value ? { "Set-Cookie": sessionCookie(value) } : {}); }
  if (req.method === "GET" && url.pathname === "/api/friends") { const viewer = requireUser(data, req, res); if (!viewer) return; const list = friendsOf(data, viewer.username).map(username => data.users.find(item => item.username === username && item.status === "approved")).filter(Boolean).map(publicUser).map(user => { const last = lastMessageOf(data, viewer.username, user.username); const unread = (data.messages || []).filter(m => m.conversation === viewer.username && m.sender === user.username && !m.read).length; return { ...user, lastMessage: last ? last.text : "", lastMessageTime: last ? last.createdAt : null, unread, online: ((Date.now() - new Date(last ? last.createdAt : 0).getTime()) < 120000 && last && last.sender === user.username) }; }).sort((a, b) => new Date(b.lastMessageTime || 0) - new Date(a.lastMessageTime || 0)); return reply(res, 200, { friends: list }); }
  if (req.method === "POST" && url.pathname === "/api/friends") { const viewer = requireUser(data, req, res); if (!viewer) return; const body = await readBody(req); const playerId = String(body.playerId || "").trim().toLowerCase().replace(/^@/, ""); if (!playerId) return reply(res, 400, { error: "آیدی بازیکن را وارد کنید." }); const target = data.users.find(item => item.username.toLowerCase() === playerId && item.status === "approved"); if (!target) return reply(res, 404, { error: "بازیکنی با این آیدی پیدا نشد." }); if (target.username === viewer.username) return reply(res, 400, { error: "نمی‌توانی خودت را اضافه کنی." }); if (isFriend(data, viewer.username, target.username)) return reply(res, 409, { error: "این بازیکن قبلاً در فهرست دوستانت است." }); viewer.friends = Array.isArray(viewer.friends) ? viewer.friends : []; target.friends = Array.isArray(target.friends) ? target.friends : []; viewer.friends.push(target.username); target.friends.push(viewer.username); notify(data, target.username, "friend", viewer.username, "@" + viewer.username + " تو را به فهرست دوستان اضافه کرد."); saveData(data); console.log(`[CHAT] Friend added | by=${viewer.username} | target=${target.username}`); return reply(res, 201, { friend: { ...publicUser(target), lastMessage: "", lastMessageTime: null, unread: 0, online: false } }); }
  if (req.method === "POST" && url.pathname === "/api/register") { const body = await readBody(req); const usernameResult = validateUsername(body.username); const username = usernameResult.username; const password = String(body.password || ""); const passwordError = validatePassword(password, body.confirmPassword); if (usernameResult.error) return reply(res, 400, { error: usernameResult.error }); if (passwordError) return reply(res, 400, { error: passwordError }); if (data.users.some(u => String(u.username || "").toLowerCase() === username) || pendingUsernames.has(username)) return reply(res, 409, { error: "این نام کاربری قبلاً استفاده شده است." }); pendingUsernames.add(username); try { const passwordHash = await hashPassword(password); const latestData = loadData(); if (latestData.users.some(u => String(u.username || "").toLowerCase() === username)) return reply(res, 409, { error: "این نام کاربری قبلاً استفاده شده است." }); const user = { id: `u-${crypto.randomUUID()}`, username, name: username, password: passwordHash, score: 0, favoriteGame: "—", avatar: username[0].toUpperCase(), status: "approved", friends: [] }; latestData.users.push(user); const createdUser = latestData.users.find(item => item.username === username); const sessionValue = token(); latestData.sessions.push({ token: sessionValue, userId: createdUser.id, createdAt: new Date().toISOString() }); saveData(latestData); console.log(`[AUTH] New user registered | username=${username} | userId=${createdUser.id} | status=APPROVED (auto)`); return reply(res, 201, { user: publicUser(createdUser), pending: false }, { "Set-Cookie": sessionCookie(sessionValue) }); } finally { pendingUsernames.delete(username); } }
  if (req.method === "GET" && url.pathname === "/api/admin/pending") { const admin = requireAdmin(data, req, res); if (!admin) return; return reply(res, 200, { pending: data.users.filter(u => u.status === "pending").map(publicUser) }); }
  if (req.method === "POST" && url.pathname === "/api/admin/approve") { const admin = requireAdmin(data, req, res); if (!admin) return; const body = await readBody(req); const username = String(body.username || "").toLowerCase(); const user = data.users.find(u => u.username === username); if (!user) return reply(res, 404, { error: "کاربر پیدا نشد." }); if (body.reject === true) { data.users = data.users.filter(u => u.username !== username); saveData(data); return reply(res, 200, { rejected: true }); } user.status = "approved"; notify(data, username, "approved", "admin", "ثبت‌نام شما تایید شد؛ خوش آمدی! 🎮"); saveData(data); return reply(res, 200, { approved: true, user: publicUser(user) }); }
  if (url.pathname === "/api/admin/stats" && req.method === "GET") { const admin = requireAdmin(data, req, res); if (!admin) return; return reply(res, 200, { stats: { users: data.users.length, pendingUsers: data.users.filter(user => user.status === "pending").length, news: (data.news || []).length, publishedNews: (data.news || []).filter(item => item.status !== "draft").length, drafts: (data.news || []).filter(item => item.status === "draft").length, messages: (data.messages || []).length } }); }
  if (url.pathname === "/api/admin/news" && req.method === "GET") { const admin = requireAdmin(data, req, res); if (!admin) return; return reply(res, 200, { news: data.news || [] }); }
  const adminNewsMatch = url.pathname.match(/^\/api\/admin\/news\/([^/]+)$/);
  if (adminNewsMatch && ["PUT", "PATCH", "DELETE"].includes(req.method)) { const admin = requireAdmin(data, req, res); if (!admin) return; const item = (data.news || []).find(entry => entry.id === adminNewsMatch[1]); if (!item) return reply(res, 404, { error: "خبر پیدا نشد." }); if (req.method === "DELETE") { data.news = data.news.filter(entry => entry.id !== item.id); saveData(data); return reply(res, 200, { deleted: true }); } const body = await readBody(req); Object.assign(item, { title: String(body.title ?? item.title).trim(), excerpt: String(body.excerpt ?? item.excerpt ?? "").trim(), text: String(body.text ?? item.text).trim(), category: String(body.category ?? item.category ?? "gaming").trim().toLowerCase(), tags: Array.isArray(body.tags) ? body.tags.slice(0, 8).map(String) : item.tags || [], status: body.status === "draft" ? "draft" : "published", image: String(body.image ?? item.image ?? ""), game: String(body.game ?? item.game ?? ""), isOfficial: body.isOfficial === true, isBreaking: body.isBreaking === true, updatedAt: new Date().toISOString() }); if (item.status === "published" && !item.publishedAt) item.publishedAt = new Date().toISOString(); saveData(data); return reply(res, 200, { news: item }); }
  if (url.pathname === "/api/admin/news" && req.method === "POST") { const admin = requireAdmin(data, req, res); if (!admin) return; const body = await readBody(req); const title = String(body.title || "").trim(); const text = String(body.text || "").trim(); if (!title || !text) return reply(res, 400, { error: "عنوان و متن خبر الزامی است." }); const now = new Date().toISOString(); const item = { id: `n-${crypto.randomUUID()}`, title, excerpt: String(body.excerpt || "").trim(), text, category: String(body.category || "gaming").trim().toLowerCase(), game: String(body.game || "").trim(), tags: Array.isArray(body.tags) ? body.tags.slice(0, 8).map(String) : [], author: admin.username, authorName: admin.name, verified: true, isOfficial: body.isOfficial === true, isBreaking: body.isBreaking === true, image: String(body.image || ""), likes: [], comments: [], createdAt: now, publishedAt: body.status === "draft" ? null : now, views: 0, status: body.status === "draft" ? "draft" : "published" }; data.news = data.news || []; data.news.unshift(item); saveData(data); return reply(res, 201, { news: item }); }
  if (req.method === "POST" && url.pathname === "/api/reports") { const reporter = requireUser(data, req, res); if (!reporter) return; const body = await readBody(req); const type = ["user", "comment", "message", "news"].includes(body.type) ? body.type : "comment"; const targetId = String(body.targetId || "").trim().slice(0, 120); const reason = String(body.reason || "").trim().slice(0, 500); if (!targetId || !reason) return reply(res, 400, { error: "شناسه و دلیل گزارش الزامی است." }); data.reports = Array.isArray(data.reports) ? data.reports : []; data.reports.push({ id: `report-${crypto.randomUUID()}`, type, targetId, reason, reporter: reporter.username, status: "pending", createdAt: new Date().toISOString() }); saveData(data); return reply(res, 201, { submitted: true, status: "pending" }); }
  if (req.method === "GET" && url.pathname === "/api/admin/reports") { const admin = requireAdmin(data, req, res); if (!admin) return; return reply(res, 200, { reports: Array.isArray(data.reports) ? data.reports : [] }); }
  if (req.method === "PATCH" && url.pathname.startsWith("/api/admin/reports/")) { const admin = requireAdmin(data, req, res); if (!admin) return; const report = (data.reports || []).find(item => item.id === decodeURIComponent(url.pathname.split("/").pop())); if (!report) return reply(res, 404, { error: "گزارش پیدا نشد." }); const body = await readBody(req); report.status = ["pending", "reviewed", "resolved", "dismissed"].includes(body.status) ? body.status : report.status; report.reviewedAt = new Date().toISOString(); report.reviewedBy = admin.username; saveData(data); return reply(res, 200, { report }); }
  if (req.method === "GET" && url.pathname === "/api/notifications") { const viewer = requireUser(data, req, res); if (!viewer) return; return reply(res, 200, { notifications: (data.notifications || []).filter(n => n.user === viewer.username).sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)) }); }
  if (req.method === "POST" && url.pathname === "/api/notifications/read") { const viewer = requireUser(data, req, res); if (!viewer) return; (data.notifications || []).forEach(n => { if (n.user === viewer.username) n.read = true; }); saveData(data); return reply(res, 200, { ok: true }); }
  if (req.method === "POST" && url.pathname === "/api/login") { const body = await readBody(req); const username = String(body.username || "").trim().toLowerCase(); const password = String(body.password || ""); const user = data.users.find(u => String(u.username || "").toLowerCase() === username); const valid = user && password.length <= 128 && await verifyPassword(password, user.password); if (!user || !valid) return reply(res, 401, { error: "نام کاربری یا رمز عبور اشتباه است." }); if (user.status === "pending") return reply(res, 403, { error: "حساب شما هنوز توسط ادمین تایید نشده است." }); const value = token(); data.sessions.push({ token: value, userId: user.id, createdAt: new Date().toISOString() }); saveData(data); return reply(res, 200, { user: publicUser(user) }, { "Set-Cookie": sessionCookie(value) }); }
  if (req.method === "POST" && url.pathname === "/api/logout") { const header = String(req.headers.authorization || ""); const cookies = String(req.headers.cookie || "").match(/(?:^|; )vexora_session=([^;]+)/); const value = header.startsWith("Bearer ") ? header.slice(7) : (cookies ? cookies[1] : ""); data.sessions = (data.sessions || []).filter(item => item.token !== value); saveData(data); return reply(res, 200, { ok: true }, { "Set-Cookie": sessionCookie("", 0) }); }
  return reply(res, 404, { error: "مسیر API پیدا نشد." });
}

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  try {
    if (url.pathname.startsWith("/api/")) return await api(req, res, url);
    if (url.pathname === "/chat" || url.pathname === "/chat.html") {
      res.writeHead(301, { "Location": "/chat-v2.html", "Cache-Control": "no-store" });
      return res.end();
    }
    const aliases = { "/admin.html": "/admin-panel.html", "/admin": "/admin-panel.html" };
    if (url.pathname === "/vexora-data.json" || /\.(log|err|bak|db)$/i.test(url.pathname) || url.pathname.startsWith("/.")) { res.writeHead(404, securityHeaders()); return res.end("Not found"); }
    let requested = decodeURIComponent(aliases[url.pathname] || (url.pathname === "/" ? "/index.html" : url.pathname));
    const file = path.resolve(ROOT, `.${requested}`);
    const relative = path.relative(ROOT, file);
    if (relative.startsWith("..") || path.isAbsolute(relative) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) { res.writeHead(404); return res.end("Not found"); }
    const ext = path.extname(file).toLowerCase();
    const prodHeaders = process.env.NODE_ENV === "production" ? { "Strict-Transport-Security": "max-age=31536000; includeSubDomains" } : {};
    if (ext === ".html") {
      const nonce = crypto.randomBytes(16).toString("base64");
      const html = fs.readFileSync(file, "utf8");
      const injected = injectNonce(html, nonce);
      res.writeHead(200, { "Content-Type": MIME[ext], ...securityHeaders(nonce), ...prodHeaders });
      return res.end(injected);
    }
    res.writeHead(200, { "Content-Type": MIME[ext] || "application/octet-stream", ...securityHeaders(), ...prodHeaders });
    fs.createReadStream(file).on("error", () => { if (!res.headersSent) reply(res, 404, { error: "فایل پیدا نشد." }); }).pipe(res);
  } catch (error) { if (!res.headersSent) reply(res, 400, { error: "درخواست نامعتبر است." }); }
});
/* بدون قفل‌شدن روی IPv4 یا IPv6، هر دو آدرس localhost و 127.0.0.1 را قبول کن. */
server.listen(PORT, "::", () => {
  console.log(`Local server is running at http://localhost:${PORT}`);
});
