import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {Ban,Check,UserPlus,X} from 'lucide-react';
import {useAuth} from '../context/AuthContext';import {createSocket} from '../services/socket';import {friendApi,reportApi,userApi} from '../services/api';import GlassCard from '../components/GlassCard';import {useToast} from '../context/ToastContext';import {Empty} from '../components/States';

export default function Chat(){
 const {user}=useAuth(),toast=useToast(),socketRef=useRef(null),peerRef=useRef('');
 const [peer,setPeerState]=useState(''),[peerPremium,setPeerPremium]=useState(false),[messages,setMessages]=useState([]),[text,setText]=useState(''),[typing,setTyping]=useState(false),[friends,setFriends]=useState([]),[incoming,setIncoming]=useState([]),[online,setOnline]=useState({}),[unread,setUnread]=useState({}),[last,setLast]=useState({}),[historyMore,setHistoryMore]=useState(false),olderRef=useRef(false);
 const setPeer=p=>{peerRef.current=p;setPeerState(p);setTyping(false);setMessages([]);if(p&&socketRef.current)socketRef.current.emit('chat:private:history',{withUser:p,limit:30})};
 const loadFriends=()=>friendApi.list().then(r=>{setFriends(r.friends||[]);setIncoming(r.incoming||[])}).catch(e=>toast.error(e.message));
 useEffect(()=>{const socket=createSocket();socketRef.current=socket;loadFriends();const onMsg=m=>{setLast(v=>({...v,[m.from===user.username?m.to:m.from]:m}));if(m.to===user.username&&m.from!==peerRef.current){setUnread(v=>({...v,[m.from]:(v[m.from]||0)+1}));return}setMessages(x=>x.some(a=>a.id===m.id)?x:[...x,m])};const onHistory=r=>{if(olderRef.current){setMessages(x=>[...(r.items||[]),...x.filter(a=>!(r.items||[]).some(b=>b.id===a.id))]);olderRef.current=false}else setMessages(r.items||[]);setHistoryMore(!!r.hasMore)};const onSeen=r=>setMessages(x=>x.map(m=>m.id===r.messageId?{...m,seen:true}:m));const onTyping=r=>{if(r.from===peerRef.current)setTyping(r.isTyping)};const onPresence=p=>setOnline(x=>({...x,[p.username]:p.online}));socket.on('chat:message',onMsg);socket.on('chat:history',onHistory);socket.on('chat:seen',onSeen);socket.on('typing',onTyping);socket.on('presence:update',onPresence);socket.on('chat:error',e=>toast.error(e.message));return()=>{socket.disconnect();socketRef.current=null}},[user.username]);
 useEffect(()=>{if(!peer){setPeerPremium(false);return}userApi.profile(peer).then(r=>setPeerPremium(!!r.user.premium?.isPremium)).catch(()=>setPeerPremium(false))},[peer]);
 useEffect(()=>{if(!peer)return;const incomingUnread=unread[peer]||0;if(incomingUnread)setUnread(v=>({...v,[peer]:0}));messages.filter(m=>m.to===user.username&&!m.seen).forEach(m=>socketRef.current?.emit('chat:private:seen',{messageId:m.id}))},[messages,peer,user.username]);
 const send=e=>{e.preventDefault();const t=text.trim();if(!t||!peer)return;socketRef.current?.emit('chat:private:send',{to:peer,text:t});setText('');socketRef.current?.emit('typing',{to:peer,isTyping:false})};
 const accept=async id=>{try{await friendApi.accept(id);await loadFriends();toast.success('درخواست دوستی تأیید شد.')}catch(e){toast.error(e.message)}};const reject=async id=>{try{await friendApi.reject(id);await loadFriends()}catch(e){toast.error(e.message)}};const block=async name=>{try{await friendApi.block(name);setFriends(v=>v.filter(f=>f.username!==name));setPeer('');toast.success('کاربر مسدود شد.')}catch(e){toast.error(e.message)}};const report=async()=>{if(!peer)return;try{await reportApi.create({kind:'user',targetId:peer,reason:'گزارش کاربر از صفحهٔ چت'});toast.success('گزارش ثبت شد.')}catch(e){toast.error(e.message)}};
 return <div className="grid gap-4 lg:grid-cols-[320px_1fr]">
  <GlassCard><div className="flex items-center justify-between"><h1 className="text-xl font-bold">گفتگوها</h1><span className="text-xs text-slate-500">{friends.length} دوست</span></div><div className="mt-4 flex gap-2"><input value={peer} onChange={e=>setPeerState(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')setPeer(e.target.value.trim())}} placeholder="username دوست" className="min-w-0 flex-1 rounded-2xl border border-white/10 bg-white/5 px-3 py-3"/><button onClick={()=>setPeer(peer.trim())} className="rounded-2xl border border-white/10 px-3" aria-label="باز کردن گفتگو"><UserPlus size={17}/></button></div>{incoming.length>0&&<div className="mt-5"><p className="mb-2 text-xs text-slate-500">درخواست‌های دوستی</p>{incoming.map(f=><div key={f.id} className="mb-2 flex items-center justify-between gap-2 rounded-2xl bg-white/5 p-3"><div><b className="text-sm">{f.displayName}</b><p className="text-[10px] text-slate-500">@{f.username}</p></div><div className="flex gap-1"><button onClick={()=>accept(f.id)} title="تأیید" className="rounded-xl p-2 text-emerald-300"><Check size={15}/></button><button onClick={()=>reject(f.id)} title="رد" className="rounded-xl p-2 text-rose-300"><X size={15}/></button></div></div>)}</div>}<div className="mt-5 space-y-2">{friends.length===0?<Empty label="هنوز دوستی نداری."/>:friends.map(f=><button key={f.username} onClick={()=>setPeer(f.username)} className={`flex w-full items-center justify-between rounded-2xl p-3 text-right ${peer===f.username?'bg-cyan-300/10':'bg-white/5 hover:bg-white/8'}`}><span className="min-w-0"><span className="block truncate font-semibold">{f.displayName}</span><span className="text-[10px] text-slate-500">@{f.username} · {online[f.username]?'آنلاین':'آفلاین'}</span>{last[f.username]&&<span className="mt-1 block max-w-48 truncate text-[10px] text-slate-500">{last[f.username].text}</span>}</span>{unread[f.username]>0&&<span className="grid min-h-6 min-w-6 place-items-center rounded-full bg-cyan-300 text-[10px] font-black text-slate-950">{unread[f.username]}</span>}</button>)}</div></GlassCard>
  <GlassCard className="flex min-h-[68vh] flex-col"><div className="flex items-center justify-between gap-3 border-b border-white/8 pb-4"><div><b>چت خصوصی</b>{peer&&<span className="mr-2 text-sm text-slate-400">@{peer}</span>}{peerPremium&&<span className="mr-2 rounded-full bg-cyan-300/10 px-2 py-0.5 text-[9px] font-bold text-cyan-200">PLUS</span>}{typing&&<span className="mr-3 text-xs text-cyan-300">در حال نوشتن...</span>}</div>{peer&&<div className="flex gap-1"><button onClick={report} title="گزارش" className="rounded-xl p-2 text-slate-400"><span className="text-xs">گزارش</span></button><button onClick={()=>block(peer)} title="مسدود کردن" className="rounded-xl p-2 text-rose-300"><Ban size={17}/></button><Link to={`/profile/${peer}`} className="rounded-xl p-2 text-cyan-200 text-xs">پروفایل</Link></div>}</div>{!peer?<div className="grid flex-1 place-items-center text-sm text-slate-500">یک دوست را انتخاب کن یا username را وارد کن.</div>:<><div className="flex-1 space-y-3 overflow-auto py-5">{historyMore&&messages[0]&&<button onClick={()=>{olderRef.current=true;socketRef.current?.emit('chat:private:history',{withUser:peer,before:messages[0].createdAt,limit:30})}} className="mx-auto block text-xs text-cyan-300">پیام‌های قدیمی‌تر</button>}{messages.length===0?<Empty label="پیامی وجود ندارد."/>:messages.map(m=><div key={m.id} className={`max-w-[82%] rounded-2xl p-3 ${m.from===user.username?'mr-auto bg-cyan-300/10':'bg-white/5'}`}><p>{m.text}</p><span className="mt-1 block text-[10px] text-slate-500">{new Date(m.createdAt).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})} · {m.from===user.username?(m.seen?'دیده شد':m.delivered?'تحویل شد':'در حال ارسال'):''}</span></div>)}</div><form onSubmit={send} className="flex gap-2"><input maxLength={2000} required value={text} onChange={e=>{setText(e.target.value);if(peer)socketRef.current?.emit('typing',{to:peer,isTyping:!!e.target.value.trim()})}} placeholder="پیام..." className="min-w-0 flex-1 rounded-2xl border border-white/10 bg-white/5 px-4 py-3"/><button className="rounded-2xl bg-cyan-300 px-5 font-bold text-slate-950">ارسال</button></form></>}</GlassCard>
 </div>
}
