import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Heart,MessageCircle,Send,Trash2} from 'lucide-react';
import GlassCard from '../components/GlassCard';
import {communityApi} from '../services/api';
import {Loading,ErrorState,Empty} from '../components/States';
import {useToast} from '../context/ToastContext';
import {useAuth} from '../context/AuthContext';

export default function Community(){
  const {user}=useAuth(),toast=useToast();const [items,setItems]=useState([]),[page,setPage]=useState(1),[hasMore,setHasMore]=useState(false),[body,setBody]=useState(''),[imageUrl,setImageUrl]=useState(''),[comments,setComments]=useState({}),[commentText,setCommentText]=useState({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[publishing,setPublishing]=useState(false);
  const load=async(p=1,append=false)=>{setError('');setLoading(true);try{const r=await communityApi.list(p);setItems(v=>append?[...v,...r.items]:r.items);setPage(r.page);setHasMore(r.hasMore)}catch(e){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const publish=async e=>{e.preventDefault();if(!body.trim())return;setPublishing(true);try{const r=await communityApi.create({body,imageUrl:imageUrl.trim()||undefined});setItems(v=>[r.post,...v]);setBody('');setImageUrl('');toast.success('پست منتشر شد.')}catch(e){toast.error(e.message)}finally{setPublishing(false)}};
  const like=async p=>{try{const r=await communityApi.like(p.id);setItems(v=>v.map(x=>x.id===p.id?{...x,...r}:x))}catch(e){toast.error(e.message)}};
  const loadComments=async id=>{try{const r=await communityApi.comments(id);setComments(v=>({...v,[id]:r.comments}))}catch(e){toast.error(e.message)}};
  const addComment=async id=>{const text=commentText[id]?.trim();if(!text)return;try{const r=await communityApi.comment(id,text);setComments(v=>({...v,[id]:r.comments}));setCommentText(v=>({...v,[id]:''}));setItems(v=>v.map(x=>x.id===id?{...x,comments:r.comments.length}:x))}catch(e){toast.error(e.message)}};
  const remove=async id=>{try{await communityApi.remove(id);setItems(v=>v.filter(x=>x.id!==id));toast.success('پست حذف شد.')}catch(e){toast.error(e.message)}};
  return <div className="mx-auto max-w-4xl space-y-5">
    <section className="glass rounded-[2rem] p-7"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs text-cyan-300">COMMUNITY</p><h1 className="text-4xl font-black">جامعهٔ گیمرها</h1><p className="mt-2 text-slate-400">پست بگذار، نظر بده و با گیمرهای دیگر آشنا شو.</p></div><Link to="/groups" className="rounded-2xl border border-white/10 px-4 py-3 text-sm text-cyan-200">گروه‌ها ←</Link></div></section>
    <GlassCard>{user?<><h2 className="text-xl font-bold">پست جدید</h2><form onSubmit={publish} className="mt-4"><textarea required maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} placeholder="الان مشغول چه بازی‌ای هستی؟" aria-label="متن پست" className="min-h-32 w-full rounded-2xl border border-white/10 bg-white/5 p-4 outline-none"/><div className="mt-3 flex items-center justify-between"><span className="text-xs text-slate-500">{body.length}/2000</span><button disabled={publishing} className="inline-flex items-center gap-2 rounded-2xl bg-cyan-300 px-4 py-3 font-bold text-slate-950"><Send size={17}/>{publishing?'در حال انتشار...':'انتشار'}</button></div></form></>:<div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold">می‌خواهی در جامعه پست بگذاری؟</h2><p className="mt-1 text-sm text-slate-500">برای انتشار پست و نظر دادن وارد حساب شو.</p></div><Link to="/login" className="rounded-2xl bg-cyan-300 px-4 py-3 font-bold text-slate-950">ورود</Link></div>}</GlassCard>
    {error?<ErrorState message={error} onRetry={()=>load(1,false)}/>:loading&&items.length===0?<Loading/>:items.length===0?<Empty label="هنوز پستی منتشر نشده."/>:<div className="space-y-4">{items.map(p=><GlassCard key={p.id}><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-full bg-white/5 text-cyan-200">{p.author.avatarUrl?<img src={p.author.avatarUrl} alt={p.author.displayName} className="h-full w-full object-cover"/>:p.author.displayName.slice(0,1)}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><Link to={`/profile/${p.author.username}`} className="font-bold hover:text-cyan-200">{p.author.displayName}</Link>{p.author.isPremium&&<span className="rounded-full bg-cyan-300/10 px-2 py-0.5 text-[9px] font-bold text-cyan-200">PLUS</span>}</div><p className="text-xs text-slate-500">@{p.author.username} · {new Date(p.createdAt).toLocaleString('fa-IR')}</p><p className="mt-4 whitespace-pre-wrap leading-8 text-slate-200">{p.body}</p>{p.imageUrl&&<img src={p.imageUrl} alt="تصویر پست" loading="lazy" className="mt-4 max-h-96 w-full rounded-2xl object-cover"/>}<div className="mt-5 flex gap-4 text-sm"><button onClick={()=>like(p)} className={`inline-flex items-center gap-1 ${p.liked?'text-rose-300':'text-slate-400'}`} aria-pressed={p.liked}><Heart size={17} fill={p.liked?'currentColor':'none'}/>{p.likes}</button><button onClick={()=>loadComments(p.id)} className="inline-flex items-center gap-1 text-slate-400"><MessageCircle size={17}/>{p.comments}</button>{user?.username===p.author.username&&<button onClick={()=>remove(p.id)} className="mr-auto text-rose-300" aria-label="حذف پست"><Trash2 size={17}/></button>}</div>{comments[p.id]&&<div className="mt-4 border-t border-white/8 pt-4"><div className="space-y-2">{comments[p.id].map(c=><div key={c.id} className="rounded-2xl bg-white/5 p-3"><div className="flex items-center gap-2"><b className="text-sm">{c.author.displayName}</b>{c.author.isPremium&&<span className="rounded-full bg-cyan-300/10 px-2 py-0.5 text-[9px] text-cyan-200">PLUS</span>}</div><p className="mt-1 text-sm text-slate-300">{c.text}</p></div>)}</div><div className="mt-3 flex gap-2"><input maxLength={500} value={commentText[p.id]||''} onChange={e=>setCommentText(v=>({...v,[p.id]:e.target.value}))} placeholder="یک نظر بنویس..." className="min-w-0 flex-1 rounded-2xl border border-white/10 bg-white/5 px-3 py-2"/><button onClick={()=>addComment(p.id)} className="rounded-2xl border border-white/10 px-4">ثبت</button></div></div>}</div></div></GlassCard>)}</div>}
    {hasMore&&<button onClick={()=>load(page+1,true)} disabled={loading} className="mx-auto block rounded-2xl border border-white/10 px-5 py-3">{loading?'در حال بارگذاری...':'پست‌های بیشتر'}</button>}
  </div>
}
