import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Gamepad2,MessageCircle,Users,Newspaper,ShieldCheck,Wifi} from 'lucide-react';
import GlassCard from '../components/GlassCard';import {useAuth} from '../context/AuthContext';import {api} from '../services/api';import {Loading,ErrorState} from '../components/States';
const games=['GTA VI','VALORANT','Minecraft','EA SPORTS FC','Counter-Strike 2','Fortnite'];
export default function Home(){const {user}=useAuth(),[overview,setOverview]=useState(null),[error,setError]=useState('');useEffect(()=>{api('/overview',{},false).then(setOverview).catch(e=>setError(e.message))},[]);return <div className="space-y-8"><section className="grid gap-6 lg:grid-cols-[1.35fr_.65fr] lg:items-stretch"><div className="glass rounded-[2rem] p-7 md:p-10"><p className="mb-3 text-sm font-bold text-cyan-300">شبکه اجتماعی گیمرها</p><h1 className="text-4xl font-black leading-tight md:text-6xl">دنیای گیم،<br/><span className="glow-text text-cyan-300">جایی برای خودت.</span></h1><p className="mt-5 max-w-2xl text-base leading-8 text-slate-300">خبر بخون، گیمرهای دیگه رو پیدا کن، پست بگذار، گروه بساز و بدون خروج از VEXORA CHAT با دوستات چت کن.</p><div className="mt-7 flex flex-wrap gap-3">{user?<Link to="/chat" className="rounded-2xl bg-cyan-300 px-5 py-3 font-bold text-slate-950">ورود به چت</Link>:<Link to="/register" className="rounded-2xl bg-cyan-300 px-5 py-3 font-bold text-slate-950">ساخت حساب</Link>}<Link to="/news" className="rounded-2xl border border-white/10 px-5 py-3 text-slate-200">مشاهده اخبار</Link></div><div className="mt-7 grid grid-cols-3 gap-2 text-center"><MiniStat n={overview?.stats.users??'—'} t="گیمر تأییدشده"/><MiniStat n={overview?.stats.news??'—'} t="خبر منتشرشده"/><MiniStat n={overview?.stats.groups??'—'} t="گروه"/></div></div><GlassCard className="flex flex-col justify-between"><div><div className="mb-4 inline-flex rounded-2xl bg-emerald-300/10 p-3 text-emerald-300"><ShieldCheck/></div><h2 className="text-2xl font-bold">ساختار حرفه‌ای</h2><p className="mt-2 leading-7 text-slate-400">احراز هویت واقعی، نقش‌های user / moderator / admin، API امن و چت لحظه‌ای.</p></div><div className="neon-line my-6"/><p className="text-sm text-slate-400">React · Vite · Tailwind · Express · PostgreSQL · MongoDB · Socket.IO · PWA</p></GlassCard></section>
 {error?<ErrorState message={error}/>:!overview?<Loading/>:<section className="grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><GlassCard><div className="mb-4 flex items-end justify-between"><div><p className="text-xs text-cyan-300">LATEST NEWS</p><h2 className="text-2xl font-bold">آخرین اخبار</h2></div><Link to="/news" className="text-sm text-cyan-200">همه اخبار ←</Link></div><div className="grid gap-3 sm:grid-cols-2">{overview.latestNews.slice(0,4).map(n=><Link key={n.id} to={`/news/${n.id}`} className="rounded-2xl bg-white/5 p-4 transition hover:bg-white/8"><div className="flex justify-between gap-2"><span className="text-xs text-cyan-300">{n.category}</span>{n.featured&&<span className="text-[10px] text-purple-300">ویژه</span>}</div><b className="mt-2 block line-clamp-2">{n.title}</b><p className="mt-2 line-clamp-2 text-xs leading-6 text-slate-500">{n.excerpt}</p></Link>)}</div></GlassCard><GlassCard><div className="mb-4 flex items-center gap-2"><Wifi className="text-emerald-300" size={20}/><div><p className="text-xs text-emerald-300">LIVE</p><h2 className="text-xl font-bold">گیمرهای آنلاین</h2></div></div>{overview.onlineUsers.length===0?<p className="text-sm text-slate-500">فعلاً کسی آنلاین ثبت نشده.</p>:<div className="space-y-2">{overview.onlineUsers.slice(0,8).map(x=><Link key={x.username} to={`/profile/${x.username}`} className="flex items-center justify-between rounded-2xl bg-white/5 p-3"><span className="text-sm">@{x.username}</span><span className="text-[10px] text-emerald-300">● آنلاین</span></Link>)}</div>}</GlassCard></section>}
 <section><div className="mb-4 flex items-end justify-between"><div><p className="text-xs text-cyan-300">POPULAR</p><h2 className="text-2xl font-bold">بازی‌های محبوب</h2></div></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{games.map(g=><GlassCard key={g} className="p-4"><Gamepad2 className="text-purple-300" size={22}/><h3 className="mt-3 font-semibold">{g}</h3></GlassCard>)}</div></section>
 <section className="grid gap-4 md:grid-cols-3"><GlassCard><Users className="text-cyan-300"/><h3 className="mt-4 font-bold">جامعه</h3><p className="mt-2 text-sm leading-7 text-slate-400">پست‌ها، لایک‌ها، کامنت‌ها و دنبال‌کردن گیمرها.</p></GlassCard><GlassCard><Newspaper className="text-purple-300"/><h3 className="mt-4 font-bold">اخبار</h3><p className="mt-2 text-sm leading-7 text-slate-400">خبرهای Gaming، Esports و Updates.</p></GlassCard><GlassCard><MessageCircle className="text-emerald-300"/><h3 className="mt-4 font-bold">چت لحظه‌ای</h3><p className="mt-2 text-sm leading-7 text-slate-400">پیام خصوصی و گروهی با وضعیت آنلاین، typing و seen.</p></GlassCard></section></div>}
function MiniStat({n,t}){return <div className="rounded-2xl bg-white/5 p-3"><b className="text-xl">{n}</b><p className="mt-1 text-[10px] text-slate-500">{t}</p></div>}
