"use strict";

document.addEventListener("DOMContentLoaded", () => {
  const api = window.torexRequest, login = document.getElementById("adminLogin"), app = document.getElementById("adminApp"), loginForm = document.getElementById("adminLoginForm"), loginError = document.getElementById("adminLoginError"), dialog = document.getElementById("newsDialog"), form = document.getElementById("newsForm"), rows = document.getElementById("newsTable"), state = document.getElementById("newsState");
  let news = [];
  const text = (id, value) => { document.getElementById(id).value = value || ""; };
  function error(message) { state.className = "error-state"; state.textContent = message; }
  function showApp() { login.classList.add("admin-hidden"); app.classList.remove("admin-hidden"); loadDashboard(); }
  async function loadDashboard() { try { const [stats, articles] = await Promise.all([api("/admin/stats"), api("/admin/news")]); news = articles.news; document.getElementById("statsGrid").innerHTML = Object.entries({ کاربران: stats.stats.users, اخبار: stats.stats.news, منتشرشده: stats.stats.publishedNews, پیش‌نویس: stats.stats.drafts, پیام‌ها: stats.stats.messages }).map(([label, value]) => `<article class="admin-stat"><span>${label}</span><strong>${Number(value).toLocaleString("fa-IR")}</strong></article>`).join(""); renderNews(); } catch (e) { if (e.message.includes("مدیر") || e.message.includes("وارد")) { login.classList.remove("admin-hidden"); app.classList.add("admin-hidden"); } else error(e.message); } }
  function renderNews() { state.className = news.length ? "admin-hidden" : "empty-state"; state.textContent = news.length ? "" : "خبری ثبت نشده است."; rows.replaceChildren(); news.forEach(item => { const row = document.createElement("tr"); const title = document.createElement("td"); title.textContent = item.title; const category = document.createElement("td"); category.textContent = item.category; const status = document.createElement("td"); status.textContent = item.status === "draft" ? "پیش‌نویس" : "منتشرشده"; const date = document.createElement("td"); date.textContent = item.publishedAt ? new Intl.DateTimeFormat("fa-IR").format(new Date(item.publishedAt)) : "—"; const actions = document.createElement("td"); actions.className = "admin-actions"; const edit = document.createElement("button"); edit.type = "button"; edit.textContent = "ویرایش"; edit.addEventListener("click", () => openEditor(item)); const remove = document.createElement("button"); remove.type = "button"; remove.className = "danger"; remove.textContent = "حذف"; remove.addEventListener("click", () => removeNews(item)); actions.append(edit, remove); row.append(title, category, status, date, actions); rows.append(row); }); }
  function openEditor(item = {}) { document.getElementById("dialogTitle").textContent = item.id ? "ویرایش خبر" : "خبر جدید"; text("newsId", item.id); text("newsTitle", item.title); text("newsCategory", item.category || "gaming"); text("newsStatus", item.status || "published"); text("newsExcerpt", item.excerpt); text("newsText", item.text); text("newsTags", (item.tags || []).join(", ")); dialog.showModal(); }
  async function saveNews(event) { event.preventDefault(); const id = document.getElementById("newsId").value; const payload = { title: document.getElementById("newsTitle").value, category: document.getElementById("newsCategory").value, status: document.getElementById("newsStatus").value, excerpt: document.getElementById("newsExcerpt").value, text: document.getElementById("newsText").value, tags: document.getElementById("newsTags").value.split(",").map(v => v.trim()).filter(Boolean) }; const button = form.querySelector("[type=submit]"); button.disabled = true; try { await api(id ? `/admin/news/${encodeURIComponent(id)}` : "/admin/news", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }); dialog.close(); await loadDashboard(); showToast("خبر با موفقیت ذخیره شد."); } catch (e) { showToast(e.message); } finally { button.disabled = false; } }
  async function removeNews(item) { if (!confirm(`خبر «${item.title}» حذف شود؟`)) return; try { await api(`/admin/news/${encodeURIComponent(item.id)}`, { method: "DELETE" }); await loadDashboard(); } catch (e) { showToast(e.message); } }
  loginForm.addEventListener("submit", async event => { event.preventDefault(); const button = loginForm.querySelector("button"); button.disabled = true; loginError.hidden = true; try { const result = await api("/login", { method: "POST", body: JSON.stringify({ phone: document.getElementById("adminPhone").value, password: document.getElementById("adminPassword").value }) }); if (result.user.role !== "admin") throw new Error("این حساب دسترسی مدیر ندارد."); localStorage.setItem("torexUser", JSON.stringify(result.user)); localStorage.setItem("torexToken", result.token); showApp(); } catch (e) { loginError.hidden = false; loginError.textContent = e.message; } finally { button.disabled = false; } });
  document.getElementById("createNewsButton").addEventListener("click", () => openEditor()); document.getElementById("cancelNewsButton").addEventListener("click", () => dialog.close()); form.addEventListener("submit", saveNews); document.getElementById("logoutButton").addEventListener("click", () => { localStorage.removeItem("torexToken"); localStorage.removeItem("torexUser"); location.reload(); });
  if (getUser()?.role === "admin" && localStorage.getItem("torexToken")) showApp();
});